version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9802:9990
    depends_on:
      - redis
      - postgresql
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - 9800:6379

  postgresql:
    image: postgres
    ports:
      - 9801:5432
    env_file:
      - pg.env
